[package]
name = "zebrachain"
version = "0.1.0"
authors = ["Jason Gerard DeRose <jasonderose@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.81"

[dependencies]
blake3 = { version = "1.5.4", features = ["zeroize"] }
chacha20poly1305 = "0.10.1"
ed25519-dalek = "2.1.1"
getrandom = "0.3.0"
pqc_dilithium = { git = "https://github.com/json420/dilithium.git", version = "0.2.0", features = ["mode3"] }

[dev-dependencies]
pqcrypto-dilithium = "0.5.0"
tempfile = "3.14.0"

