[package]
name = "zebrachain"
version = "0.1.0-pre.0"
description = """
ZebraChain is a logged, quantum safe signing protocol designed to replace the long lived asymmetric
key pairs used to sign software releases (and to sign other super important stuff).
"""
authors = ["Jason Gerard DeRose <jasonderose@gmail.com>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/zebrachain"
repository = "https://github.com/zebrafactory/zebrachain"
keywords = ["pqc", "awesomeness"]
categories = ["cryptography"]
edition = "2024"
rust-version = "1.86"

[dependencies]
blake3 = { version = "1.5.4", features = ["zeroize"] }
chacha20poly1305 = { version = "0.10.1", default-features = false, features = ["alloc"] }
ed25519-dalek = "2.1.1"
getrandom = "0.3.0"
ml-dsa = { version = "=0.0.4", default-features = false, features = ["zeroize"] }
signature = "2.2.0"
zeroize = "1.8.1"

[dev-dependencies]
tempfile = "3.14.0"

[profile.dev]
opt-level = 2
