name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  do-it-on-ubuntu:
    name: Build and Test on Ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose --release

  do-it-on-macos:
    name: Build and Test on MacOS
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose --release

